# 监控的网络接口
interface: eth0 

# 汇总时间间隔
summary_time: 5 

# Web 服务端口
port: 8080 

# 启用 Web 服务
enable: true 

# 最大数据包数量
max_packet_count: 10000 

# GeoIP 数据库路径
# geoip_path: GeoLite2-City.mmdb 
geoip_path: 

# 监控规则（收集命中规则的所有数据包）
rules:
  - rule_name: "示例规则，请勿使用"
    # 支持精确端口和端口范围
    port: [22, 3306, 6379, 5432, "21-23"] 
    ip:
      - "1.1.1.1" # 精确IP
      - "3.3.3.0/24" # CIDR
      - "GEOIP:美国" # 国家为美国的IP流量均进行收集
      - "CITY:成都" # 城市为成都的IP流量均进行收集
      - "GEOIP:!中国" # 不包含中国的所有IP流量均进行收集
    mac:
      - "00:00:00:00:00:01" # 仅支持精确MAC
    # 支持的IP协议请查看internal/enum/enum.go文件
    ip_protocol: 
      - tcp
      - udp
      - icmp
      - igmp
    # 支持的以太网协议类型请查看internal/enum/enum.go文件
    eth_type: 
      - ipv4
      - ipv6
      - arp

# 黑名单，黑名单将传输映射至内核态，仅支持精确MAC、IP
# 在 XDP 阶段进行流量阻断，性能极高
black:
  mac:
    - "00:00:00:00:00:01"
  ipv4:
    - "1.1.1.1"
  ipv6:
    - "2400:da00::6666"
